
version: '3.9'
services:
  app:
    container_name: app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '9000:80'
    expose:
      - '9000'
    depends_on:
      - db
    links:
      - db

  
  db:
      image: mysql:latest
      container_name: db
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: XXX
        MYSQL_DATABASE: PHALCON_REST_API
        MYSQL_USER: ZZZ
        MYSQL_PASSWORD: WWW
      ports:
        - "3307:3306"
        - "33060:33060"
      working_dir: /var/lib/mysql
      volumes:
        - "./mysql-data:/var/lib/mysql:rw"
        #- mysql-data:/var/lib/mysql


volumes:
  mysql-data:
    